import { GlobalStyles } from '@/style';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'PokemonQuiz',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <GlobalStyles />
      <body>{children}</body>
    </html>
  );
}
